version: '3.8'

services:
  app_db:
    container_name: app_db
    image: postgres:latest
    environment:
      POSTGRES_DB: workoutdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
